imu_joint_manipulator_1_config:
  imu_type: "imu"
  imu_topic: "/imu/data_raw_1"
  imu_frame: "cobra_body_6"
  odom_frame: "odom"


imu_joint_manipulator_2_config:
  imu_type: "imu"
  imu_topic: "/imu2/data_raw_2"
  imu_frame: "cobra_body_3"
  odom_frame: "odom"


fusion1:
  state_variables: [x, y, yaw]
  imu: imu_joint_manipulator_1_config
  odom0: [imu1_frame, odom]

fusion2:
  state_variables: [x, y, yaw]
  imu: imu_joint_manipulator_2_config
  odom0: [imu2_frame, odom]
